projectTitle = "United Armory"
modId = "united_armory"
modVersion = "1.0.0"
group = "com.theendercore"
githubRepo = "theendercore/UnitedArmory"
discordServerInviteId = "KZ5Q364hEg"
authors = [ "TheEnderCore" ]
majorMinecraftVersion = ">=1.21"
minecraftVersion = "1.21.1"
fabricLoaderVersion = "0.18.3"
fabricApiVersion = "0.116.7+1.21.1"
fabricLangKotlinVersion = "1.13.8+kotlin.2.3.0"
license = "MIT"
modules = [ ]
modDescription = "Coisson mod "
# Modmenu badges, values can be: [ library, deprecated ]
badges = [ ]
disableKotlin = false

[mappings]
    # You have 7 mapping types
    # MOJANG: The official Mojang mappings
    # YARN: Yarn mappings
    # PARCHMENT: Parchment mappings
    # QUILT: Quilt mappings
    # MOJPARCH: Parchment layered on top of the official Mojang mappings
    # MOJYARN: Yarn layered on top of the official Mojang mappings
    # CUSTOM: Custom mapping jar. Uses mappings version as file location
    type = "MOJANG"
    version = "1.21.1"
